version: '3'

services:
  backend:
    build:
      context: ./Back-End
      dockerfile: Dockerfile
    image: 63070106/my-backend_image:1.0
  frontend:
    build:
      context: ./Front-End
      dockerfile: Dockerfile
    image: 63070106/my-frontend_image:1.0
